### ISSUE TITLE
Mekanism: Weapons (mekaweapons) encountered an error during the enqueue_imc event phase

### ISSUE THREAD

**Issue by jdjcool1** [omeranha/MekaWeapons#10]
-- MOD mekaweapons --
Details:
	Mod File: /F:/MCM/PrismLauncher/instances/1.20.1(1)/.minecraft/mods/MekanismWeapons-1.20.1-1.3.jar
	Failure message: Mekanism: Weapons (mekaweapons) encountered an error during the enqueue_imc event phase
		java.lang.NoSuchFieldError: SPACE_BREATHING_UNIT
	Mod Version: 1.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: SPACE_BREATHING_UNIT
log file attached 
[message.txt](https://github.com/omeranha/MekaWeapons/files/14060594/message.txt)

**Comment by Lapis256** [comment]
It seems to be incompatible with Ad Astra: Giselle Addon v6.4.
