### ISSUE TITLE
Crash during enqueueIMC

### ISSUE THREAD

**Issue by DragonS0u1623** [omeranha/MekaWeapons#14]
I tried loading the latest version and when I launched I got the error for crash during enqueueIMC.
The errored field is Oxygen_proof_unit

MC Logs: https://mclo.gs/dnFLdWT

**Comment by omeranha** [comment]
hi! make sure you're using AdAstra Giselle Addon 6.4 (latest version)
do a backup of your world (mod dev tip) and try again

**Comment by Virtual-Enchanter** [comment]
I have the same crash, i solve it by outdating meka weapon mod but i would like to look at new content of the mod update :(
