### ISSUE TITLE
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods

### ISSUE THREAD

**Issue by SirTwsted** [omeranha/MekaWeapons#18]
As the title says:
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods.

I am using MC v1.21 with NEOForge v21.0.114, also tried it with v21.0.113

![Mekanism ERROR after update](https://github.com/user-attachments/assets/dcb593d2-f769-4d0d-bb35-0be207fafdfe)

![Screenshot_313](https://github.com/user-attachments/assets/c501adce-6bda-4a93-a1bc-938f733027e6)

end transmission:

**Comment by Y0ungSandwich** [comment]
Heres a crash report from my pack crashing with the same errors.

https://pastebin.com/eyeA2YaA

**Comment by arrester-002** [comment]
The latest version is also not compatible
[crash-2024-08-08_00.14.54-fml.txt](https://github.com/user-attachments/files/16530658/crash-2024-08-08_00.14.54-fml.txt)

**Comment by omeranha** [comment]
hello, last update of the addon should fix any bugs related to this, thanks for the issue
