### ISSUE TITLE
Fails to load on 1.21.1, with mekanism 10.7.7

### ISSUE THREAD

**Issue by WhitePhant0m** [omeranha/MekaWeapons#24]
https://mclo.gs/jGk4L81

**Comment by omeranha** [comment]
the 1.21.1 support is going to be done when #25 is complete, going the fast I can, thanks for playing

**Comment by Phoupraw** [comment]
May I ask if there has been any progress?

**Comment by omeranha** [comment]
the mod has been updated to 1.21.1, check the latest release:
https://www.curseforge.com/minecraft/mc-mods/mekanism-weapons/files/5906398
closing it, thank you
