### ISSUE TITLE
[QUESTION] change how many upgrade weapon can take

### ISSUE THREAD

**Issue by YassaaaTU** [omeranha/MekaWeapons#31]
Is it possible to change how many weapon upgrades I can apply on a weapon in the config or via datapacks?

If not it would be a nice addition/feature

**Comment by Achille004** [comment]
Before the radial update, yes. But now it's a no.
It COULD be done, but it won't have any icons, names, etc..
Also all the registry names are hard-coded, so it would need a sh*tload of work

**Comment by Achille004** [comment]
I'll close this issue as inapplicable, if you have other questions feel free to ask.

**Comment by Achille004** [comment]
I'll close this issue as inapplicable, if you have other questions feel free to ask.
