### ISSUE TITLE
Module Arrow velocity unit doesn't exists

### ISSUE THREAD

**Issue by Strange05** [omeranha/MekaWeapons#8]
Downloaded the mod for 1.20.1 with forge 47.2.0, to use im my modpack but i get a kubejs recipe error and vanilla error saying item that this module doesn't exists. i tryied with a brand new instace with just mekanism, the basic addons  like generators and tools but the item still doesn't exists. 
[latest.log](https://github.com/omeranha/MekaWeapons/files/14032256/latest.log)

**Comment by omeranha** [comment]
hi, sorry for late response, but the arrow velocity it is in wip, it is necessary to solve some bugs, for that reason it is not available in the game

**Comment by Fred-Redstone-2** [comment]
Any updates on this?

**Comment by Th3Fanbus** [comment]
Would it make sense to add a condition to the recipe? Something like this seems to work for me (`MekaWeapons-1.12.1-2.0.1`, KubeJS no longer complains about the arrow velocity unit):

```
{
  "type":"minecraft:crafting_shaped",
  "conditions": [
    {
      "type": "neoforge:item_exists",
      "item": "mekaweapons:module_arrowvelocity_unit"
    }
  ]
  "result":{
    "id":"mekaweapons:module_arrowvelocity_unit"
  },
  "pattern":[ "sbs", "ama", "ppp" ],
  "key":{
    "m":{ "item": "mekanism:module_base" },
    "p":{ "item":"mekanism:pellet_polonium" },
    "b":{ "item":"minecraft:arrow" },
    "a":{ "item":"mekanism:alloy_reinforced" },
    "s":{ "item":"mekanism:upgrade_speed" }
  }
}
```

(referencing duplicate issue #19 for visibility)
