### ISSUE TITLE
Magnetizer isn`t working on curios

### ISSUE THREAD

**Issue by DarkBRrvv** [omeranha/MekaWeapons#9]
When I try to use the magnetizer in the Curios slot, its slot does not appear.
What do I have to do?

**Comment by omeranha** [comment]
just tested with the new update (which should not impact in the curios implementation), and worked correctly
are you sure both have installed curios and tested properly? @kokloler @DarkBRrvv

**Comment by kokloler** [comment]
If you'd like, I can call you on discord to show you what I'm doing. My discord account is @kokloler

**Comment by omeranha** [comment]
@kokloler I sent you a friend request

**Comment by omeranha** [comment]
fixed in latest update of 1.19.2
